// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// CancelOrderByUuidNoContent is response for CancelOrderByUuid operation.
type CancelOrderByUuidNoContent struct{}

func (*CancelOrderByUuidNoContent) cancelOrderByUuidRes() {}

// Ref: #/components/schemas/components_create_order_request
type ComponentsCreateOrderRequest struct {
	// Список UUID деталей/товаров для заказа.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
}

// GetPartUuids returns the value of PartUuids.
func (s *ComponentsCreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetUserUUID returns the value of UserUUID.
func (s *ComponentsCreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// SetPartUuids sets the value of PartUuids.
func (s *ComponentsCreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetUserUUID sets the value of UserUUID.
func (s *ComponentsCreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// Ref: #/components/schemas/components_create_order_response
type ComponentsCreateOrderResponse struct {
	// UUID заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Общая стоимость заказа.
	TotalPrice float32 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *ComponentsCreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *ComponentsCreateOrderResponse) GetTotalPrice() float32 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *ComponentsCreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *ComponentsCreateOrderResponse) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

func (*ComponentsCreateOrderResponse) createOrderRes() {}

// Статус заказа.
// Ref: #/components/schemas/components_enums_order_status
type ComponentsEnumsOrderStatus string

const (
	ComponentsEnumsOrderStatusASSEMBLED      ComponentsEnumsOrderStatus = "ASSEMBLED"
	ComponentsEnumsOrderStatusPENDINGPAYMENT ComponentsEnumsOrderStatus = "PENDING_PAYMENT"
	ComponentsEnumsOrderStatusPAID           ComponentsEnumsOrderStatus = "PAID"
	ComponentsEnumsOrderStatusCANCELLED      ComponentsEnumsOrderStatus = "CANCELLED"
)

// AllValues returns all ComponentsEnumsOrderStatus values.
func (ComponentsEnumsOrderStatus) AllValues() []ComponentsEnumsOrderStatus {
	return []ComponentsEnumsOrderStatus{
		ComponentsEnumsOrderStatusASSEMBLED,
		ComponentsEnumsOrderStatusPENDINGPAYMENT,
		ComponentsEnumsOrderStatusPAID,
		ComponentsEnumsOrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ComponentsEnumsOrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case ComponentsEnumsOrderStatusASSEMBLED:
		return []byte(s), nil
	case ComponentsEnumsOrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case ComponentsEnumsOrderStatusPAID:
		return []byte(s), nil
	case ComponentsEnumsOrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ComponentsEnumsOrderStatus) UnmarshalText(data []byte) error {
	switch ComponentsEnumsOrderStatus(data) {
	case ComponentsEnumsOrderStatusASSEMBLED:
		*s = ComponentsEnumsOrderStatusASSEMBLED
		return nil
	case ComponentsEnumsOrderStatusPENDINGPAYMENT:
		*s = ComponentsEnumsOrderStatusPENDINGPAYMENT
		return nil
	case ComponentsEnumsOrderStatusPAID:
		*s = ComponentsEnumsOrderStatusPAID
		return nil
	case ComponentsEnumsOrderStatusCANCELLED:
		*s = ComponentsEnumsOrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Метод оплаты.
// Ref: #/components/schemas/components_enums_payment_method
type ComponentsEnumsPaymentMethod string

const (
	ComponentsEnumsPaymentMethodUNKNOWN       ComponentsEnumsPaymentMethod = "UNKNOWN"
	ComponentsEnumsPaymentMethodCARD          ComponentsEnumsPaymentMethod = "CARD"
	ComponentsEnumsPaymentMethodSBP           ComponentsEnumsPaymentMethod = "SBP"
	ComponentsEnumsPaymentMethodCREDITCARD    ComponentsEnumsPaymentMethod = "CREDIT_CARD"
	ComponentsEnumsPaymentMethodINVESTORMONEY ComponentsEnumsPaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all ComponentsEnumsPaymentMethod values.
func (ComponentsEnumsPaymentMethod) AllValues() []ComponentsEnumsPaymentMethod {
	return []ComponentsEnumsPaymentMethod{
		ComponentsEnumsPaymentMethodUNKNOWN,
		ComponentsEnumsPaymentMethodCARD,
		ComponentsEnumsPaymentMethodSBP,
		ComponentsEnumsPaymentMethodCREDITCARD,
		ComponentsEnumsPaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ComponentsEnumsPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case ComponentsEnumsPaymentMethodUNKNOWN:
		return []byte(s), nil
	case ComponentsEnumsPaymentMethodCARD:
		return []byte(s), nil
	case ComponentsEnumsPaymentMethodSBP:
		return []byte(s), nil
	case ComponentsEnumsPaymentMethodCREDITCARD:
		return []byte(s), nil
	case ComponentsEnumsPaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ComponentsEnumsPaymentMethod) UnmarshalText(data []byte) error {
	switch ComponentsEnumsPaymentMethod(data) {
	case ComponentsEnumsPaymentMethodUNKNOWN:
		*s = ComponentsEnumsPaymentMethodUNKNOWN
		return nil
	case ComponentsEnumsPaymentMethodCARD:
		*s = ComponentsEnumsPaymentMethodCARD
		return nil
	case ComponentsEnumsPaymentMethodSBP:
		*s = ComponentsEnumsPaymentMethodSBP
		return nil
	case ComponentsEnumsPaymentMethodCREDITCARD:
		*s = ComponentsEnumsPaymentMethodCREDITCARD
		return nil
	case ComponentsEnumsPaymentMethodINVESTORMONEY:
		*s = ComponentsEnumsPaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/components_errors_bad_gateway_error
type ComponentsErrorsBadGatewayError struct {
	// Тип ошибки.
	Error string `json:"error"`
	// Сообщение об ошибке.
	Message string `json:"message"`
	// Уникальный идентификатор запроса.
	RequestID OptString `json:"request_id"`
	// Время возникновения ошибки.
	Timestamp time.Time `json:"timestamp"`
	// Название вышестоящего сервиса.
	UpstreamService OptString `json:"upstream_service"`
}

// GetError returns the value of Error.
func (s *ComponentsErrorsBadGatewayError) GetError() string {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsBadGatewayError) GetMessage() string {
	return s.Message
}

// GetRequestID returns the value of RequestID.
func (s *ComponentsErrorsBadGatewayError) GetRequestID() OptString {
	return s.RequestID
}

// GetTimestamp returns the value of Timestamp.
func (s *ComponentsErrorsBadGatewayError) GetTimestamp() time.Time {
	return s.Timestamp
}

// GetUpstreamService returns the value of UpstreamService.
func (s *ComponentsErrorsBadGatewayError) GetUpstreamService() OptString {
	return s.UpstreamService
}

// SetError sets the value of Error.
func (s *ComponentsErrorsBadGatewayError) SetError(val string) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsBadGatewayError) SetMessage(val string) {
	s.Message = val
}

// SetRequestID sets the value of RequestID.
func (s *ComponentsErrorsBadGatewayError) SetRequestID(val OptString) {
	s.RequestID = val
}

// SetTimestamp sets the value of Timestamp.
func (s *ComponentsErrorsBadGatewayError) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

// SetUpstreamService sets the value of UpstreamService.
func (s *ComponentsErrorsBadGatewayError) SetUpstreamService(val OptString) {
	s.UpstreamService = val
}

func (*ComponentsErrorsBadGatewayError) cancelOrderByUuidRes() {}
func (*ComponentsErrorsBadGatewayError) createOrderRes()       {}
func (*ComponentsErrorsBadGatewayError) getOrderByUuidRes()    {}
func (*ComponentsErrorsBadGatewayError) payOrderRes()          {}

// Ref: #/components/schemas/components_errors_bad_request_error
type ComponentsErrorsBadRequestError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ComponentsErrorsBadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsBadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ComponentsErrorsBadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsBadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*ComponentsErrorsBadRequestError) createOrderRes() {}

// Ref: #/components/schemas/components_errors_conflict_error
type ComponentsErrorsConflictError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ComponentsErrorsConflictError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ComponentsErrorsConflictError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ComponentsErrorsConflictError) cancelOrderByUuidRes() {}

// Ref: #/components/schemas/components_errors_forbidden_error
type ComponentsErrorsForbiddenError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ComponentsErrorsForbiddenError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsForbiddenError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ComponentsErrorsForbiddenError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsForbiddenError) SetMessage(val string) {
	s.Message = val
}

func (*ComponentsErrorsForbiddenError) cancelOrderByUuidRes() {}
func (*ComponentsErrorsForbiddenError) createOrderRes()       {}
func (*ComponentsErrorsForbiddenError) payOrderRes()          {}

// Ref: #/components/schemas/components_errors_generic_error
type ComponentsErrorsGenericError struct {
	// Сообщение об ошибке.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsGenericError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsGenericError) SetMessage(val string) {
	s.Message = val
}

// ComponentsErrorsGenericErrorStatusCode wraps ComponentsErrorsGenericError with StatusCode.
type ComponentsErrorsGenericErrorStatusCode struct {
	StatusCode int
	Response   ComponentsErrorsGenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *ComponentsErrorsGenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ComponentsErrorsGenericErrorStatusCode) GetResponse() ComponentsErrorsGenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ComponentsErrorsGenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ComponentsErrorsGenericErrorStatusCode) SetResponse(val ComponentsErrorsGenericError) {
	s.Response = val
}

func (*ComponentsErrorsGenericErrorStatusCode) cancelOrderByUuidRes() {}
func (*ComponentsErrorsGenericErrorStatusCode) createOrderRes()       {}
func (*ComponentsErrorsGenericErrorStatusCode) payOrderRes()          {}

// Ref: #/components/schemas/components_errors_internal_server_error
type ComponentsErrorsInternalServerError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ComponentsErrorsInternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsInternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ComponentsErrorsInternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*ComponentsErrorsInternalServerError) createOrderRes() {}

// Ref: #/components/schemas/components_errors_not_found_error
type ComponentsErrorsNotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ComponentsErrorsNotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsNotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ComponentsErrorsNotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsNotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*ComponentsErrorsNotFoundError) cancelOrderByUuidRes() {}
func (*ComponentsErrorsNotFoundError) getOrderByUuidRes()    {}
func (*ComponentsErrorsNotFoundError) payOrderRes()          {}

// Ref: #/components/schemas/components_errors_rate_limit_error
type ComponentsErrorsRateLimitError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ComponentsErrorsRateLimitError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsRateLimitError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ComponentsErrorsRateLimitError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsRateLimitError) SetMessage(val string) {
	s.Message = val
}

func (*ComponentsErrorsRateLimitError) cancelOrderByUuidRes() {}
func (*ComponentsErrorsRateLimitError) createOrderRes()       {}
func (*ComponentsErrorsRateLimitError) payOrderRes()          {}

// Ref: #/components/schemas/components_errors_service_unavailable_error
type ComponentsErrorsServiceUnavailableError struct {
	// Тип ошибки.
	Error string `json:"error"`
	// Сообщение об ошибке.
	Message string `json:"message"`
	// Время в секундах до повтора запроса.
	RetryAfter OptInt `json:"retry_after"`
	// Название недоступного сервиса.
	Service OptString `json:"service"`
	// Время возникновения ошибки.
	Timestamp time.Time `json:"timestamp"`
}

// GetError returns the value of Error.
func (s *ComponentsErrorsServiceUnavailableError) GetError() string {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsServiceUnavailableError) GetMessage() string {
	return s.Message
}

// GetRetryAfter returns the value of RetryAfter.
func (s *ComponentsErrorsServiceUnavailableError) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetService returns the value of Service.
func (s *ComponentsErrorsServiceUnavailableError) GetService() OptString {
	return s.Service
}

// GetTimestamp returns the value of Timestamp.
func (s *ComponentsErrorsServiceUnavailableError) GetTimestamp() time.Time {
	return s.Timestamp
}

// SetError sets the value of Error.
func (s *ComponentsErrorsServiceUnavailableError) SetError(val string) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsServiceUnavailableError) SetMessage(val string) {
	s.Message = val
}

// SetRetryAfter sets the value of RetryAfter.
func (s *ComponentsErrorsServiceUnavailableError) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetService sets the value of Service.
func (s *ComponentsErrorsServiceUnavailableError) SetService(val OptString) {
	s.Service = val
}

// SetTimestamp sets the value of Timestamp.
func (s *ComponentsErrorsServiceUnavailableError) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

func (*ComponentsErrorsServiceUnavailableError) cancelOrderByUuidRes() {}
func (*ComponentsErrorsServiceUnavailableError) createOrderRes()       {}
func (*ComponentsErrorsServiceUnavailableError) getOrderByUuidRes()    {}
func (*ComponentsErrorsServiceUnavailableError) payOrderRes()          {}

// Ref: #/components/schemas/components_errors_unauthorized_error
type ComponentsErrorsUnauthorizedError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ComponentsErrorsUnauthorizedError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsUnauthorizedError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ComponentsErrorsUnauthorizedError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsUnauthorizedError) SetMessage(val string) {
	s.Message = val
}

func (*ComponentsErrorsUnauthorizedError) cancelOrderByUuidRes() {}
func (*ComponentsErrorsUnauthorizedError) createOrderRes()       {}
func (*ComponentsErrorsUnauthorizedError) payOrderRes()          {}

// Ref: #/components/schemas/components_errors_validation_error
type ComponentsErrorsValidationError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Сообщение об ошибке.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ComponentsErrorsValidationError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ComponentsErrorsValidationError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ComponentsErrorsValidationError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ComponentsErrorsValidationError) SetMessage(val string) {
	s.Message = val
}

func (*ComponentsErrorsValidationError) createOrderRes() {}

// Ref: #/components/schemas/components_get_order_response
type ComponentsGetOrderResponse struct {
	// Сообщение о результате операции.
	Message OptString          `json:"message"`
	Order   ComponentsOrderDto `json:"order"`
}

// GetMessage returns the value of Message.
func (s *ComponentsGetOrderResponse) GetMessage() OptString {
	return s.Message
}

// GetOrder returns the value of Order.
func (s *ComponentsGetOrderResponse) GetOrder() ComponentsOrderDto {
	return s.Order
}

// SetMessage sets the value of Message.
func (s *ComponentsGetOrderResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetOrder sets the value of Order.
func (s *ComponentsGetOrderResponse) SetOrder(val ComponentsOrderDto) {
	s.Order = val
}

func (*ComponentsGetOrderResponse) getOrderByUuidRes() {}

// Ref: #/components/schemas/components_order_dto
type ComponentsOrderDto struct {
	// Уникальный идентификатор заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Список UUID деталей/товаров в заказе.
	PartUuids     []uuid.UUID                  `json:"part_uuids"`
	PaymentMethod ComponentsEnumsPaymentMethod `json:"payment_method"`
	Status        ComponentsEnumsOrderStatus   `json:"status"`
	// Общая стоимость заказа.
	TotalPrice float32 `json:"total_price"`
	// Уникальный идентификатор транзакции.
	TransactionUUID OptUUID `json:"transaction_uuid"`
	// Уникальный идентификатор пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *ComponentsOrderDto) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *ComponentsOrderDto) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *ComponentsOrderDto) GetPaymentMethod() ComponentsEnumsPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *ComponentsOrderDto) GetStatus() ComponentsEnumsOrderStatus {
	return s.Status
}

// GetTotalPrice returns the value of TotalPrice.
func (s *ComponentsOrderDto) GetTotalPrice() float32 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *ComponentsOrderDto) GetTransactionUUID() OptUUID {
	return s.TransactionUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *ComponentsOrderDto) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// SetOrderUUID sets the value of OrderUUID.
func (s *ComponentsOrderDto) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *ComponentsOrderDto) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *ComponentsOrderDto) SetPaymentMethod(val ComponentsEnumsPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *ComponentsOrderDto) SetStatus(val ComponentsEnumsOrderStatus) {
	s.Status = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *ComponentsOrderDto) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *ComponentsOrderDto) SetTransactionUUID(val OptUUID) {
	s.TransactionUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *ComponentsOrderDto) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// Ref: #/components/schemas/components_pay_order_request
type ComponentsPayOrderRequest struct {
	PaymentMethod ComponentsEnumsPaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *ComponentsPayOrderRequest) GetPaymentMethod() ComponentsEnumsPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *ComponentsPayOrderRequest) SetPaymentMethod(val ComponentsEnumsPaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/components_pay_order_response
type ComponentsPayOrderResponse struct {
	// UUID транзакции.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *ComponentsPayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *ComponentsPayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*ComponentsPayOrderResponse) payOrderRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
